services:
  - type: web
    name: resume-mine
    env: node
    buildCommand: bun install && bun run build
    startCommand: bun run preview
    envVars:
      - key: NODE_ENV
        value: production
