services:
  - type: web
    name: resume-mine
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
